name: Check  File Types in _post

on:
  pull_request:
    branches: [ main ]

jobs:
  check-post-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Check file types in _posts directory
        run: |
          for file in _posts/*; do
            if [[ ! "$file" == *.md ]]; then
              echo "Error: Found non-markdown file in _posts directory: $file"
              exit 1
            fi
          done

