name: Jekyll Site CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          npm install -g markdownlint-cli

      - name: Lint Markdown files
        run: |
          echo "{
            \"default\": true,
            \"MD040\": false
          }" > .markdownlint.json
          markdownlint "**/*.md" --config .markdownlint.json

      - name: Build the Jekyll site
        run: bundle exec jekyll build

      - name: Run HTML Proofer
        run: bundle exec htmlproofer ./_site --check-external-hash --allow-hash-href

