name: Jekyll check .md syntax

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          npm install -g markdownlint-cli

      - name: Lint Markdown files
        run: |
          markdownlint "**/*.md"

      - name: Build the Jekyll site
        run: bundle exec jekyll build

      - name: Run HTML Proofer
        run: bundle exec htmlproofer ./_site --check-external-hash --allow-hash-href

